In [1]:
import pandas as pd
import numpy as np
import xlsxwriter

In [3]:
df1 = pd.read_excel('../DataFiles/Preservation Units.xlsx')

In [4]:
df1.head()

SR  RRT  RRQ  Begin ARM  End ARM Begin SRMP End SRMP  \
0   2  NaN  NaN       3.96     4.50       3.83     4.37   
1   2  NaN  NaN       4.53     4.80       4.40     4.67   
2   2  NaN  NaN       5.15     8.65       5.02     8.52   
3   2  NaN  NaN       8.65     8.93       8.52     8.80   
4   2  NaN  NaN       8.93    10.33       8.80    10.25   

  Direction To Inventory     Region Surface Type     ...       \
0                      B  Northwest          ACP     ...        
1                      B  Northwest          ACP     ...        
2                      B  Northwest          ACP     ...        
3                      B  Northwest          ACP     ...        
4                      B  Northwest          ACP     ...        

   Due Year Trigger  Percent Far Past Due Percent Past Due Percent Due  \
0               PSC                     0             7.41       92.59   
1               PSC                     0            37.04       62.96   
2               PSC                     0             0.00       93.61   
3               PSC                     0             0.00      100.00   
4               PRC                     0            35.71       35.71   

  Percent Near Future Due  Percent Future Due   AADT  Avg Construction Date  \
0                    0.00                0.00  31462             1983-10-01   
1                    0.00                0.00  23939             1983-10-01   
2                    6.39                0.00  20098             1983-08-24   
3                    0.00                0.00  17598             1983-10-01   
4                   21.43                7.14  25316             1960-07-05   

   Avg Major Rehab Date  Speed Limit  
0            1998-06-08           60  
1            1998-06-08           60  
2            1998-06-08           60  
3            1998-06-08           60  
4            1998-06-08           60  

[5 rows x 26 columns]

In [6]:
df2 = pd.read_csv('../tables/Preservation Units.txt', header = None)

In [8]:
len(df1) == len(df2)

True

In [9]:
df2.columns = df1.columns

In [10]:
df2.head()

SR  RRT  RRQ  Begin ARM  End ARM Begin SRMP End SRMP  \
0   2  NaN  NaN       3.96     4.50       3.83     4.37   
1   2  NaN  NaN       4.53     4.80       4.40     4.67   
2   2  NaN  NaN       5.15     8.65       5.02     8.52   
3   2  NaN  NaN       8.65     8.93       8.52     8.80   
4   2  NaN  NaN       8.93    10.33       8.80    10.25   

  Direction To Inventory     Region Surface Type     ...       \
0                      B  Northwest          ACP     ...        
1                      B  Northwest          ACP     ...        
2                      B  Northwest          ACP     ...        
3                      B  Northwest          ACP     ...        
4                      B  Northwest          ACP     ...        

   Due Year Trigger  Percent Far Past Due  Percent Past Due Percent Due  \
0               PSC                     0              7.41       92.59   
1               PSC                     0             37.04       62.96   
2               PSC                     0              0.00       93.61   
3               PSC                     0              0.00      100.00   
4               PRC                     0             35.71       35.71   

  Percent Near Future Due  Percent Future Due   AADT  Avg Construction Date  \
0                    0.00                0.00  31462      10/1/1983 0:00:00   
1                    0.00                0.00  23939      10/1/1983 0:00:00   
2                    6.39                0.00  20098      8/24/1983 0:00:00   
3                    0.00                0.00  17598      10/1/1983 0:00:00   
4                   21.43                7.14  25316       7/5/1960 0:00:00   

   Avg Major Rehab Date  Speed Limit  
0      6/8/1998 0:00:00           60  
1      6/8/1998 0:00:00           60  
2      6/8/1998 0:00:00           60  
3      6/8/1998 0:00:00           60  
4      6/8/1998 0:00:00           60  

[5 rows x 26 columns]

In [12]:
df2[df2.SR==2]['Begin ARM'].describe()

count    306.000000
mean     134.302124
std      106.613026
min        0.000000
25%       44.185000
50%      103.020000
75%      267.130000
max      326.210000
Name: Begin ARM, dtype: float64

In [14]:
df2[df2.SR==2]['Speed Limit'].unique()

array([60, 55, 45, 35, 50, 30, 40, 25, 65])

In [13]:
print len(df2)

8645


In [36]:
firstList = np.arange(df2[df2.SR==2]['Begin ARM'].max())
firstIndex = np.repeat(2, len(firstList))
ds = pd.DataFrame(firstList, firstIndex)
for sr in df2.SR.unique()[1:]:
    mx = df2[df2.SR==sr]['Begin ARM'].max()
    milepost = np.arange(mx)
    index = np.repeat(sr, len(milepost))
    sdf = pd.DataFrame(milepost, index)
    ds = pd.concat([ds, sdf])

In [41]:
ds.columns = ['milepost']
ds.tail(9)

milepost
970         9
970        10
971         0
971         1
971         2
971         3
971         4
971         5
971         6

In [42]:
df2.columns

Index([u'SR', u'RRT', u'RRQ', u'Begin ARM', u'End ARM', u'Begin SRMP',
       u'End SRMP', u'Direction To Inventory', u'Region', u'Surface Type',
       u'Length', u'Lane Miles', u'NHS', u'Federal Functional Class', u'ID',
       u'Due Year', u'Due Year Trigger', u'Percent Far Past Due',
       u'Percent Past Due', u'Percent Due', u'Percent Near Future Due',
       u'Percent Future Due', u'AADT', u'Avg Construction Date',
       u'Avg Major Rehab Date', u'Speed Limit'],
      dtype='object')

In [43]:
df = df2[['SR', 'Begin ARM', 'Speed Limit']]

In [44]:
df.head(10)

SR  Begin ARM  Speed Limit
0   2       3.96           60
1   2       4.53           60
2   2       5.15           60
3   2       8.65           60
4   2       8.93           60
5   2      10.33           60
6   2      12.55           55
7   2      13.10           55
8   2      13.40           55
9   2      13.50           45

In [60]:
ds['SR'] = ds.index

In [61]:
ds.index = np.arange(len(ds))

In [62]:
ds.head()

milepost  SR
0         0   2
1         1   2
2         2   2
3         3   2
4         4   2

In [63]:
def getSpeed(row):
    sr = row['SR']
    mp = row['milepost']
    result = np.array(df[(df.SR == sr) & (df['Begin ARM'] >= mp) & (df['Begin ARM'] < (mp+1))]['Speed Limit'])
    if len(result) == 0:
        return None
    else:
        return result[0]

In [64]:
ds['SpeedLimit'] = ds.apply(getSpeed, axis = 1)

In [66]:
ds.head(10)

milepost  SR  SpeedLimit
0         0   2          55
1         1   2         NaN
2         2   2          55
3         3   2          60
4         4   2          60
5         5   2          60
6         6   2         NaN
7         7   2         NaN
8         8   2          60
9         9   2         NaN

In [67]:
ds['ID'] = ds.index

In [82]:
def ImputeMissingSpeed(row):
    speed = row['SpeedLimit']
    mile  = row['milepost']
    index = int(row['ID'])
    if np.isnan(speed) & (mile == 0):
        ds.loc[index, 'SpeedLimit'] = 0
        return None
    elif np.isnan(speed):
        ds.loc[index, 'SpeedLimit'] = ds.loc[(index-1), 'SpeedLimit']
        return None
    else:
        return None

In [83]:
result = ds.apply(ImputeMissingSpeed, axis = 1)

In [84]:
ds.head(20)

milepost  SR  SpeedLimit  ID
0          0   2          55   0
1          1   2          55   1
2          2   2          55   2
3          3   2          60   3
4          4   2          60   4
5          5   2          60   5
6          6   2          60   6
7          7   2          60   7
8          8   2          60   8
9          9   2          60   9
10        10   2          60  10
11        11   2          60  11
12        12   2          55  12
13        13   2          55  13
14        14   2          45  14
15        15   2          55  15
16        16   2          55  16
17        17   2          55  17
18        18   2          55  18
19        19   2          55  19

In [86]:
print len(ds[ds['SpeedLimit'] == 0])

0


In [87]:
ds.SpeedLimit.unique()

array([ 55.,  60.,  45.,  50.,  35.,  30.,  40.,  25.,  65.,  70.])

In [91]:
ds2 = pd.read_csv('../modelDatasets/ndata.csv')

In [92]:
ds2.columns

Index([u'Unnamed: 0', u'UID', u'IsBridge', u'Lane Surface Type', u'LaneMiles',
       u'Region_x', u'FFClass', u'SurfaceTypeCode', u'STDescription',
       u'TreatBaseCode', u'TreatBaseDescription', u'TBThick', u'untrthick',
       u'Y_ESAL', u'MajorRehabYear', u'Cum_ESAL', u'SURFTHK', u'ULT',
       u'TSfThick', u'tmin', u'tmax', u'cumESALs', u'IRIsi', u'Alli', u'Long',
       u'E_Alli', u'E_Long', u'prep', u'MinT', u'MaxT', u'FTCycles',
       u'actbthick', u'pctbthick', u'ftprep', u'BA', u'AA'],
      dtype='object')

In [95]:
#Importing the dataframe with unique ids
idf = pd.read_csv('../FInalDatasets/Contracts.csv')
idf = idf.drop_duplicates(subset = ['UID'])

In [96]:
print len(idf)
idf.head()

18098


Unnamed: 0  SR    BA    EA  bs  es  UID  RRT  RRQ  Begin ARM  \
0           0   2  0.00  0.13   0   1    1  NaN  NaN       0.00   
4           5   2  1.49  1.55  14  15   15  NaN  NaN       1.49   
5           7   2  2.64  2.75  26  27   27  NaN  NaN       2.64   
6           9   2  3.64  3.75  36  37   37  NaN  NaN       3.64   
7          10   2  6.50  6.66  65  66   66  NaN  NaN       6.50   

        ...        Exception Code    Exception Description Surface Type Code  \
0       ...                   NaN                      NaN                BA   
4       ...                    42  BRIDGE DECK RESURFACING                BA   
5       ...                   NaN                      NaN                AA   
6       ...                   NaN                      NaN                BA   
7       ...                   NaN                      NaN                PA   

  Surface Type Description Surface Thickness Treat Base Type Code  \
0      ACP CLASS B AR4000W              0.25                    3   
4      ACP CLASS B AR4000W              0.15                    0   
5      ACP CLASS A AR4000W              0.35                    0   
6      ACP CLASS B AR4000W              0.70                    3   
7                     PCCP              0.00                    0   

                Treat Base Type Description Treat Base Thickness  \
0  Asphalt Treated Base Or Bituminous Admix                  0.5   
4                                       NaN                  0.0   
5                                       NaN                  0.0   
6  Asphalt Treated Base Or Bituminous Admix                  0.3   
7                                       NaN                  0.0   

   UTreat Base Thickness Sequence Number  
0                   0.25               0  
4                   0.00               1  
5                   0.00               1  
6                   0.00               0  
7                   0.00               0  

[5 rows x 30 columns]

In [98]:
print len(ds2[ds2.UID.isin(idf.UID)])
print len(ds2)

4083
4083


In [102]:
sdf = idf[['SR', 'BA', 'UID']]
sdf.columns = ['SR', 'BMP', 'UID']

In [103]:
data = pd.merge(ds2, sdf, how = 'left', left_on = ['UID'], right_on = 'UID')

In [104]:
data.head()

Unnamed: 0   UID  IsBridge Lane Surface Type  LaneMiles       Region_x  \
0           0   650         0               ACP       0.20  North Central   
1           1  2651         0               ACP       0.30        Eastern   
2           2  1193         0               ACP       0.20  North Central   
3           3  1070         0               ACP       0.20  North Central   
4           4  1192         0               ACP       0.12  North Central   

                          FFClass SurfaceTypeCode            STDescription  \
0  Rural Other Principal Arterial              D2  ACP CLASS 1/2IN PG58-34   
1  Rural Other Principal Arterial              BA      ACP CLASS B AR4000W   
2  Urban Other Freeway/Expressway              BA      ACP CLASS B AR4000W   
3  Rural Other Freeway/Expressway              BA      ACP CLASS B AR4000W   
4  Urban Other Freeway/Expressway              H2  ACP CLASS 1/2IN PG70-28   

   TreatBaseCode   ...    MinT       MaxT  FTCycles  actbthick  pctbthick  \
0              0   ...   -5.48  21.600000        38          0          0   
1              0   ...   -8.73  30.420000        84          0          0   
2              0   ...   -4.85  33.630001        21          0          0   
3              0   ...   -6.27  32.840000        21          0          0   
4              0   ...   -4.85  33.630001        21          0          0   

         ftprep  BA  AA  SR     BMP  
0  78155.358887   0   0   2   64.77  
1  28866.599487   1   0   2  265.06  
2   4056.779846   1   0   2  119.23  
3   6786.360077   1   0   2  107.03  
4   4056.779846   0   0   2  119.17  

[5 rows x 38 columns]

In [105]:
def getSpeed(row):
    sr = row['SR']
    mp = int(row['BMP'])
    req = np.array(ds[(ds.SR == sr) & (ds.milepost==mp)]['SpeedLimit'])
    if len(req) == 0:
        return None
    return req[0]

In [108]:
data['SpeedLimit'] = data.apply(getSpeed, axis = 1)

In [109]:
data.head()

Unnamed: 0   UID  IsBridge Lane Surface Type  LaneMiles       Region_x  \
0           0   650         0               ACP       0.20  North Central   
1           1  2651         0               ACP       0.30        Eastern   
2           2  1193         0               ACP       0.20  North Central   
3           3  1070         0               ACP       0.20  North Central   
4           4  1192         0               ACP       0.12  North Central   

                          FFClass SurfaceTypeCode            STDescription  \
0  Rural Other Principal Arterial              D2  ACP CLASS 1/2IN PG58-34   
1  Rural Other Principal Arterial              BA      ACP CLASS B AR4000W   
2  Urban Other Freeway/Expressway              BA      ACP CLASS B AR4000W   
3  Rural Other Freeway/Expressway              BA      ACP CLASS B AR4000W   
4  Urban Other Freeway/Expressway              H2  ACP CLASS 1/2IN PG70-28   

   TreatBaseCode     ...           MaxT  FTCycles  actbthick  pctbthick  \
0              0     ...      21.600000        38          0          0   
1              0     ...      30.420000        84          0          0   
2              0     ...      33.630001        21          0          0   
3              0     ...      32.840000        21          0          0   
4              0     ...      33.630001        21          0          0   

         ftprep  BA  AA  SR     BMP  SpeedLimit  
0  78155.358887   0   0   2   64.77          35  
1  28866.599487   1   0   2  265.06          60  
2   4056.779846   1   0   2  119.23          45  
3   6786.360077   1   0   2  107.03          60  
4   4056.779846   0   0   2  119.17          45  

[5 rows x 39 columns]

In [110]:
data.SpeedLimit.unique()

array([ 35.,  60.,  45.,  55.,  30.,  50.,  70.,  40.,  25.,  65.,  nan])

In [111]:
print len(data[data.SpeedLimit.isnull()==1])

18


In [116]:
dataset = data.sort(columns = ['SR', 'BMP'])

/Users/Alan/anaconda2/lib/python2.7/site-packages/ipykernel/__main__.py:1: FutureWarning: sort(columns=....) is deprecated, use sort_values(by=.....)
  if __name__ == '__main__':


In [120]:
dataset.index = np.arange(len(data))
dataset['idx'] = np.arange(len(data))

In [121]:
dataset.head()

Unnamed: 0  UID  IsBridge Lane Surface Type  LaneMiles   Region_x  \
0         712    1         0               ACP       0.36    Eastern   
1         635   24         1               ACP       0.15  Northwest   
2        1704   27         0               ACP       0.20  Northwest   
3         671   33         0               ACP       0.20  Northwest   
4         706   28         0               ACP       0.20  Northwest   

                          FFClass SurfaceTypeCode        STDescription  \
0  Urban Other Principal Arterial              BA  ACP CLASS B AR4000W   
1  Urban Other Freeway/Expressway              PA                 PCCP   
2  Urban Other Freeway/Expressway              AA  ACP CLASS A AR4000W   
3  Urban Other Freeway/Expressway              BA  ACP CLASS B AR4000W   
4  Urban Other Freeway/Expressway              AA  ACP CLASS A AR4000W   

   TreatBaseCode ...  FTCycles  actbthick  pctbthick       ftprep  BA  AA  SR  \
0              3 ...         5        0.5          0  4208.250122   1   0   2   
1              0 ...         5        0.0          0  4534.049988   0   0   2   
2              0 ...         5        0.0          0  4534.049988   0   1   2   
3              0 ...         5        0.0          0  4534.049988   1   0   2   
4              0 ...         5        0.0          0  4534.049988   0   1   2   

    BMP  SpeedLimit  idx  
0  0.00          55    0  
1  2.19          55    1  
2  2.64          55    2  
3  2.75          55    3  
4  2.75          55    4  

[5 rows x 40 columns]

In [127]:
def ImputeSpeed(row):
    speed = row['SpeedLimit']
    idx   = row['idx']
    sr    = row['SR']
    mp    = row['BMP']
    if np.isnan(speed) & (mp == 0):
        dataset.loc[idx, 'SpeedLimit'] = 0
        return None
    elif np.isnan(speed):
        dataset.loc[idx, 'SpeedLimit'] = dataset.loc[(idx-1), 'SpeedLimit']
        return None     
    else:
        return None

In [128]:
res = dataset.apply(ImputeSpeed, axis = 1)

In [131]:
print len(dataset[dataset.SpeedLimit ==0])

0


In [132]:
dataset.SpeedLimit.unique()

array([ 55.,  60.,  45.,  50.,  35.,  30.,  65.,  25.,  40.,  70.])

In [133]:
dataset.columns

Index([u'Unnamed: 0', u'UID', u'IsBridge', u'Lane Surface Type', u'LaneMiles',
       u'Region_x', u'FFClass', u'SurfaceTypeCode', u'STDescription',
       u'TreatBaseCode', u'TreatBaseDescription', u'TBThick', u'untrthick',
       u'Y_ESAL', u'MajorRehabYear', u'Cum_ESAL', u'SURFTHK', u'ULT',
       u'TSfThick', u'tmin', u'tmax', u'cumESALs', u'IRIsi', u'Alli', u'Long',
       u'E_Alli', u'E_Long', u'prep', u'MinT', u'MaxT', u'FTCycles',
       u'actbthick', u'pctbthick', u'ftprep', u'BA', u'AA', u'SR', u'BMP',
       u'SpeedLimit', u'idx'],
      dtype='object')

In [136]:
rdat = dataset[[ u'UID', u'IsBridge', u'Lane Surface Type', u'LaneMiles',
       u'Region_x', u'FFClass', u'SurfaceTypeCode', u'STDescription',
       u'TreatBaseCode', u'TreatBaseDescription', u'TBThick', u'untrthick',
       u'Y_ESAL', u'MajorRehabYear', u'Cum_ESAL', u'SURFTHK', u'ULT',
       u'TSfThick', u'tmin', u'tmax', u'cumESALs', u'IRIsi', u'Alli', u'Long',
       u'E_Alli', u'E_Long', u'prep', u'MinT', u'MaxT', u'FTCycles',
       u'actbthick', u'pctbthick', u'ftprep', u'BA', u'AA', u'SR', u'BMP',
       u'SpeedLimit']]

In [137]:
rdat.to_csv('../modelDatasets/MCdata.csv')

In [138]:
speeds = np.sort(dataset.SpeedLimit.unique())

In [139]:
speeds

array([ 25.,  30.,  35.,  40.,  45.,  50.,  55.,  60.,  65.,  70.])