In [7]:
import pandas as pd
import numpy as np

In [3]:
index = pd.date_range('1/1/2000', periods =8)

In [4]:
print index

DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04',
               '2000-01-05', '2000-01-06', '2000-01-07', '2000-01-08'],
              dtype='datetime64[ns]', freq='D', tz=None)


In [8]:
s = pd.Series(np.random.randn(5), index = ['a', 'b', 'c', 'd', 'e'])

In [10]:
df = pd.DataFrame(np.random.randn(8, 3), index=index, columns=['A', 'B', 'C'])

In [13]:
df.head()

A         B         C
2000-01-01  0.063456  0.595962 -0.889474
2000-01-02 -0.607321  0.274135  0.268047
2000-01-03 -1.614957  2.691400  0.633754
2000-01-04 -1.249139 -1.324084  1.424176
2000-01-05  1.390799 -0.438260 -0.902505

In [14]:
df.tail()

A         B         C
2000-01-04 -1.249139 -1.324084  1.424176
2000-01-05  1.390799 -0.438260 -0.902505
2000-01-06 -0.537521  0.939041  0.740086
2000-01-07  0.059877 -2.517697  0.641023
2000-01-08 -1.307688  1.606307  1.776352

In [15]:
s.values

array([ 0.64295175,  1.13637955, -2.33597422,  1.39614425,  0.23065536])

In [16]:
print s

a    0.642952
b    1.136380
c   -2.335974
d    1.396144
e    0.230655
dtype: float64


In [17]:
df.values

array([[ 0.06345578,  0.59596193, -0.88947384],
       [-0.60732054,  0.27413482,  0.26804698],
       [-1.61495696,  2.69139987,  0.63375425],
       [-1.24913929, -1.32408369,  1.42417588],
       [ 1.39079948, -0.4382605 , -0.90250521],
       [-0.53752098,  0.93904134,  0.74008583],
       [ 0.05987725, -2.51769667,  0.64102319],
       [-1.30768826,  1.60630745,  1.77635208]])

In [20]:
wp = pd.Panel(np.random.randn(2, 5, 4), items=['Item1', 'Item2'], major_axis=pd.date_range('1/1/2000', periods=5),
              minor_axis=['A', 'B', 'C', 'D'])

In [22]:
wp

<class 'pandas.core.panel.Panel'>
Dimensions: 2 (items) x 5 (major_axis) x 4 (minor_axis)
Items axis: Item1 to Item2
Major_axis axis: 2000-01-01 00:00:00 to 2000-01-05 00:00:00
Minor_axis axis: A to D

In [23]:
wp.values

array([[[-0.11544681, -0.69053159,  0.46036764, -2.01307461],
        [-1.29242784, -0.17755021, -0.30078065, -0.19331505],
        [ 0.85709539, -1.04212325,  0.72418959,  0.79075142],
        [-0.83566634, -0.24746285, -1.01032778, -1.41278424],
        [-1.01368302, -0.01189232,  1.62978153,  0.07919881]],

       [[ 0.10796005,  0.31194736,  1.63637305, -1.14684048],
        [ 1.42398079, -0.69055891,  0.6603617 , -2.09498552],
        [ 0.14361168, -0.27398882,  0.85106907,  0.6476769 ],
        [ 0.13087417, -0.833734  , -0.50265492, -0.11061637],
        [-0.2336453 , -0.34490575, -0.8386056 ,  1.14390032]]])